feat: Refactorized SettingsVC
Pengabdi-Tjoean/SLAP-Sounds-Like-A-Plan pull request #79
Opened 2022-12-01 18:44 UTC by jasonskycore

feat: Made some changes to TableViewCell in SettingsVC
feat: Added PushNotificationVC

2022-12-01 18:48 UTC, gremlinflat commented on Sounds Like A Plan/Features/Profile-old/SwitchTableViewCell.swift
> +    static let identifier = "SwitchTableViewCell"
identifier should be lowercased

2022-12-01 18:49 UTC, gremlinflat commented on Sounds Like A Plan/Features/Profile-old/SettingsViewController.swift
> +        let rightButton = UIBarButtonItem(barButtonSystemItem: .done, target: self, action: #selector(onDoneButtonTapped))
did___tapped

2022-12-01 18:50 UTC, jasonskycore commented on Sounds Like A Plan/Features/Profile-old/SettingsViewController.swift
> +        let rightButton = UIBarButtonItem(barButtonSystemItem: .done, target: self, action: #selector(onDoneButtonTapped))
siap noted

2022-12-01 18:51 UTC, jasonskycore commented on Sounds Like A Plan/Features/Profile-old/SwitchTableViewCell.swift
> +    static let identifier = "SwitchTableViewCell"
siap noted🙏🙏

2022-12-01 18:54 UTC, gremlinflat commented on Sounds Like A Plan/Features/Profile-old/SettingsViewController.swift
> +    func configure() {
why dont you append it on line 19? 
e.g

let settings: [Settings] = [
     Setting(type: "PREFERENCES", content: ["Push notifications"]),
     Setting(type: "ACCOUNT SETTINGS", content: ["Personal Information", "Privacy"]),
     .......
]

2022-12-01 18:55 UTC, gremlinflat requested changes

2022-12-01 18:55 UTC, gremlinflat commented on Sounds Like A Plan/Features/Profile-old/PushNotificationViewController.swift
> +    func configure() {
sama kyk diatas

2022-12-01 18:55 UTC, gremlinflat commented on Sounds Like A Plan/Features/Profile-new/ProfileViewController.swift
>      @objc func onSettingButtonTapped() {
did__tapped

2022-12-01 18:56 UTC, jasonskycore commented on Sounds Like A Plan/Features/Profile-old/SettingsViewController.swift
> +    func configure() {
noted sir, will make it tidier 🙏

2022-12-01 19:54 UTC, jasonskycore commented on Sounds Like A Plan/Features/Profile-old/PushNotificationViewController.swift
> +    func configure() {
ok

2022-12-02 07:42 UTC, gremlinflat approved these changes
LGTM

2022-12-02 07:42 UTC, merged